# Step1 匯入資料

In [1]:
from sklearn.datasets import fetch_mldata
mnist=fetch_mldata('MNIST original')
mnist

{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: mnist-original',
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'target': array([0., 0., 0., ..., 9., 9., 9.])}

In [2]:
X, y = mnist["data"], mnist["target"]
print(X.shape)
print(y.shape)

(70000, 784)
(70000,)


# Step2 選取70%資料做預測

In [3]:
import numpy as np
shuffle_index = np.random.permutation(70000) #洗牌?
#70000*0.7 = 49000
X_train, X_test, y_train, y_test = X[shuffle_index[:49000]], X[shuffle_index[49000:]], y[shuffle_index[:49000]], y[shuffle_index[49000:]] 

In [4]:
#test
import numpy as np 
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.array([ 2, 0])
print(a[b])

[[ 9 10 11 12]
 [ 1  2  3  4]]


# Step3 平均分配資料

In [5]:
from collections import Counter
count_data= Counter(y_train)
print(count_data)

Counter({1.0: 5489, 7.0: 5098, 3.0: 5065, 2.0: 4893, 9.0: 4872, 0.0: 4826, 4.0: 4787, 8.0: 4781, 6.0: 4769, 5.0: 4420})


# Step4 naive_bayes

In [8]:
from sklearn.naive_bayes import BernoulliNB
import datetime

starttime = datetime.datetime.now()

BernoulliNB_clf = BernoulliNB()
BernoulliNB_clf.fit(X_train, y_train)

BeriNB_mnist_pre = BernoulliNB_clf.predict(X_train)

from sklearn import metrics
accuracy = metrics.accuracy_score(y_train, BeriNB_mnist_pre)
print(accuracy)
endtime = datetime.datetime.now()
print ('time: ',(endtime-starttime))

0.8334897959183674
time:  0:00:00.824192


# Step5 混淆矩陣

In [9]:
import pandas as pd
pd.crosstab(y_train, BeriNB_mnist_pre,rownames=['label'],colnames=['predict'])

predict   0.0   1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
label                                                              
0.0      4316     2    19    36    15   214    78     1   137     8
1.0         0  5266    48    12     3    58    21     3    69     9
2.0        79    69  4028   112   103    14   198    44   232    14
3.0        44   104   214  4057    13   116    45    67   254   151
4.0         8    32    32     0  3871    20    76    23    95   630
5.0       126    52    40   652   132  3092    95    24    85   122
6.0        60   131    83     3    37   145  4278     0    30     2
7.0        17   108    36    16   126     7     1  4308   104   375
8.0        69   169    76   386    55   129    30    13  3667   187
9.0        58    70    22    62   351    20     2   199   130  3958

# Step6 交叉驗證

In [12]:
from sklearn.model_selection import cross_val_score
import datetime
starttime = datetime.datetime.now()

score = cross_val_score(BernoulliNB_clf, X_train, y_train, cv=5, scoring="accuracy")
print(score)
endtime = datetime.datetime.now()
print ('time: ',(endtime-starttime))

[0.83057936 0.83238115 0.83540816 0.83670137 0.82799102]
time:  0:00:02.268033
