1. 定義數列
2. 選取數列
3. 運算

# Numpy

In [2]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))   
print(a.ndim)
print(a.data)             # Print out memory address
print(a.shape)            # Prints "(3,)" 可看出多少維度
print("------- 1D ---------")
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
print("------ 2D ----------")
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   
print("------ 3D ----------")
c = np.array([[[ 1 , 2 , 3 , 4] ,[ 5 , 6 , 7 , 8]],[[ 1,  2,  3 , 4],[ 9 ,10 ,11 ,12]]])
print(c)
print(c.shape) 
print(c[0,0,2])

<class 'numpy.ndarray'>
1
(3,)
------- 1D ---------
1 2 3
[5 2 3]
------ 2D ----------
(2, 3)
1 2 4
------ 3D ----------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
(2, 2, 4)
3


In [10]:
from pprint import pprint
b = np.array([[1,2,3],[4,5,6],[7,8,9]])    
pprint(b)
print(b[:2,1:2])
print(b[2::])
print(b[:,2])
print(b.shape)
print('--------------------')
print(b.ndim)
#print(help(a))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
[[2]
 [5]]
[[7 8 9]]
[3 6 9]
(3, 3)
--------------------
2


In [18]:
from pprint import pprint
a = np.array([[1,1],[1,1]])
b = np.array([[2,2],[2,2]])
pprint(a)
pprint(b)
print('---------------------')
print(a+b)
print('---------------------')
print(a-b)
print('---------------------')
print(a*b)
print('---------------------')
print(a/b)
print('---------------------')
print(a.dot(b))

array([[1, 1],
       [1, 1]])
array([[2, 2],
       [2, 2]])
---------------------
[[3 3]
 [3 3]]
---------------------
[[-1 -1]
 [-1 -1]]
---------------------
[[2 2]
 [2 2]]
---------------------
[[0.5 0.5]
 [0.5 0.5]]
---------------------
[[4 4]
 [4 4]]


# Pandas

## list

In [6]:
import pandas as pd
shop_arr = [["Movies", 46],["Sports", 8], ["Coding", 12], ["Fishing",12], ["Dancing",6], ["cooking",8]]
print(shop_arr)
df = pd.DataFrame(shop_arr, columns = ["name", "numCount"]) # 指定欄標籤名稱  
print(df)

[['Movies', 46], ['Sports', 8], ['Coding', 12], ['Fishing', 12], ['Dancing', 6], ['cooking', 8]]
      name  numCount
0   Movies        46
1   Sports         8
2   Coding        12
3  Fishing        12
4  Dancing         6
5  cooking         8


## dict

In [5]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]
shopping_dict = {"groups": groups,  
        "num": num
       }
print(shopping_dict)
dict_df = pd.DataFrame(shopping_dict)
print(dict_df)

{'groups': ['Movies', 'Sports', 'Coding', 'Fishing', 'Dancing', 'cooking'], 'num': [46, 8, 12, 12, 6, 58]}
    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


In [12]:
print('印出num欄位')
print(dict_df["num"]) # 各組的人數 
print('*********************')
print('印出groups欄位')
print(dict_df["groups"]) # 各組的人數 
print('*********************')
print('部分印出groups欄位')
print(dict_df.loc[2:3])
print('*********************')
print('數值判斷')
print(dict_df['num']>12)

印出num欄位
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
*********************
印出groups欄位
0     Movies
1     Sports
2     Coding
3    Fishing
4    Dancing
5    cooking
Name: groups, dtype: object
*********************
部分印出groups欄位
    groups  num
2   Coding   12
3  Fishing   12
*********************
數值判斷
0     True
1    False
2    False
3    False
4    False
5     True
Name: num, dtype: bool


# Preprocessing

### 遺漏值

In [43]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd  
df = pd.read_csv('data\shop_list.csv')  
print(df)
print('**********')
print(df.info())
print('**********')
print(df['shop name'].value_counts())
print('**********')
import numpy as np
print(df.describe())

   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3       NaN   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         NaN
**********
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
shop id       5 non-null int64
shop name     4 non-null object
maket size    4 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes
None
**********
Yahoo       1
Pchome      1
Costco      1
Wal mart    1
Name: shop name, dtype: int64
**********
        shop id    maket size
count  5.000000  4.000000e+00
mean   3.000000  1.700000e+06
std    1.581139  1.122497e+06
min    1.000000  3.000000e+05
25%    2.000000  1.200000e+06
50%    3.000000  1.750000e+06
75%    4.000000  2.250000e+06
max    5.000000  3.000000e+06


In [21]:
print(df.isnull()) # 判斷哪些店名是遺失值  

   shop id  shop name  maket size
0    False      False       False
1    False      False       False
2    False       True       False
3    False      False       False
4    False      False        True


In [28]:
print("---依欄位填補遺失值")  
filled_value = df.fillna(0) # 有遺失值的觀測值填補 0  
print(filled_value)  

---依欄位填補遺失值
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3         0   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         0.0


In [25]:
print("---依欄位填補遺失值")  
filled_value_column = df.fillna({"shop name": "NULL", "maket size":10}) # 依欄位填補遺失值  
print(filled_value_column)

---依欄位填補遺失值
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3      NULL   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo        10.0


In [26]:
print("---有遺失值的觀測值都刪除 ")  
drop_value = df.dropna() # 有遺失值的觀測值都刪除  
print(drop_value)

---有遺失值的觀測值都刪除 
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
3        4    Pchome    300000.0


In [36]:
# 寫入 CSV File
import pandas as pd 

print(filled_value)
columns = ['shop id' ,'shop name' , 'maket size']
writer_df = pd.DataFrame(filled_value, columns=columns)
writer_df.to_csv("data\RE_shop_list.csv", index=False)

   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3         0   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         0.0
