# Numpy

In [148]:
import numpy as np 
np.__version__

"""
ref:
1. http://cs231n.github.io/python-numpy-tutorial/#python-classes
2. https://www.datacamp.com/community/tutorials/python-numpy-tutorial#array
"""

'\nref:\n1. http://cs231n.github.io/python-numpy-tutorial/#python-classes\n2. https://www.datacamp.com/community/tutorials/python-numpy-tutorial#array\n'

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))   
print(a.ndim)
print(a.data)             # Print out memory address
print(a.shape)            # Prints "(3,)" 可看出多少維度
print("------- 1D ---------")
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
print("------ 2D ----------")
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   
print("------ 3D ----------")
c = np.array([[[ 1 , 2 , 3 , 4] ,[ 5 , 6 , 7 , 8]],[[ 1,  2,  3 , 4],[ 9 ,10 ,11 ,12]]])
print(c)
print(c.shape) 
print(c[0,0,2]) 


<class 'numpy.ndarray'>
1
(3,)
------- 1D ---------
1 2 3
[5 2 3]
------ 2D ----------
(2, 3)
1 2 4
------ 3D ----------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
(2, 2, 4)
3


In [5]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a) 
print('--------------------')
b = np.ones((1,2))    # Create an array of all ones
print(b)  
print('--------------------')
d = np.eye(3)         # Create a 2x2 identity matrix
print(d)  

[[0. 0.]
 [0. 0.]]
--------------------
[[1. 1.]]
--------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Slicing

In [2]:
import numpy as np 
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('--------------------')
print(a.data)
print('--------------------')
print(a.shape)
print('--------------------')
print(a.ndim)
print(help(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
--------------------
(3, 4)
--------------------
2
Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes b

In [7]:
b = a[:2, 1:3]
print(b)
print('--------------------')
print(b.data)
print('--------------------')
print(a[0, 1]) 
print('--------------------b')
b[0, 0] = 77
print(b)
print('--------------------b+b')
print(b+b)
print('--------------------內積')
print(b.dot(b)) #內積
print('--------------------')
print(a[0, 1]) 

[[77  3]
 [ 6  7]]
--------------------
--------------------
77
--------------------b
[[77  3]
 [ 6  7]]
--------------------b+b
[[154   6]
 [ 12  14]]
--------------------內積
[[5947  252]
 [ 504   67]]
--------------------
77


# Pandas 

### 資料前處理以及 DataFrame 所用

#  1.1建立 Series

## array

In [23]:
import pandas as pd # 引用套件並縮寫為 pd
cars = ["BMW", "BENZ", "Toyota", "Nissan", "Lexus"]

select = pd.Series(cars)  
print(select)  

0       BMW
1      BENZ
2    Toyota
3    Nissan
4     Lexus
dtype: object


## dict

In [27]:
import pandas as pd

dict_data = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict_data, index = dict.keys()) # 排序與原 dict 相同  
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']]) 

Taipei
=====
1
=====
factory    Taipei
sensor2         2
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         1
sensor3         3
dtype: object


## 資料為單一資料

In [29]:
import pandas as pd

cars = "BENZ"  
select = pd.Series(cars, index = range(5))  
print(select) 

0    BENZ
1    BENZ
2    BENZ
3    BENZ
4    BENZ
dtype: object


# 1.2 Series 的操作

## 資料選擇與篩選

In [34]:
import pandas as pd

dict_data = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor1": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict_data, index = dict.keys()) # 排序與原 dict 相同  
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']])  

Taipei
=====
2
=====
factory    Taipei
sensor2       NaN
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         2
sensor3         3
dtype: object


## 資料切片 

In [35]:
import pandas as pd

dict = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict, index = dict.keys()) # 排序與原 dict 相同  
print(select[:2])  
print("=====")  
print(select['sensor2':])  

factory    Taipei
sensor1         1
dtype: object
=====
sensor2    2
sensor3    3
sensor4    4
sensor5    5
dtype: object


# 2.DataFrame

## dict

In [37]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
       }

select_df = pd.DataFrame(dict)

print(select_df) # 看看資料框的外觀  

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


## Array

In [1]:
import pandas as pd

arr = [["Movies", 46],["Sports", 8], ["Coding", 12], ["Fishing",12], ["Dancing",6], ["cooking",8]]

df = pd.DataFrame(arr, columns = ["name", "num"]) # 指定欄標籤名稱  
print(df)  

      name  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking    8


# 2.2 DataFrame 的操作

In [5]:
# Pandas 的 data frame 資料結構有一些方法或屬性

import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(dict)
print("---shape")
print(select_df.shape) # 回傳列數與欄數  
print("---describe")  
print(select_df.describe()) # 回傳描述性統計  
print("---head")  
print(select_df.head(3)) # 回傳前三筆觀測值  
print("---tail")  
print(select_df.tail(3)) # 回傳後三筆觀測值  
print("---columns")  
print(select_df.columns) # 回傳欄位名稱  
print("---index")  
print(select_df.index) # 回傳 index  
print("---info")  
print(select_df.info) # 回傳資料內容  

---shape
(6, 2)
---describe
             num
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
---head
   groups  num
0  Movies   46
1  Sports    8
2  Coding   12
---tail
    groups  num
3  Fishing   12
4  Dancing    6
5  cooking   58
---columns
Index(['groups', 'num'], dtype='object')
---index
RangeIndex(start=0, stop=6, step=1)
---info
<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58>


##  資料選擇與篩選 

## iloc

In [13]:
import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict_data = {"groups": groups,  
        "num": num
       }
select_df = pd.DataFrame(dict_data)

print(select_df.info)
print("---[2]")  
print(select_df.iloc[2]) # 第二列  
print("---[2, 1]")  
print(select_df.iloc[2, 1]) # 第一列第二欄：組的人數  
print("---[0:1,:]")  
print(select_df.iloc[0:1,:]) # 第一列：組的組名與人數  
print("---[:,1]")  
print(select_df.iloc[:,1]) # 第二欄：各組的人數  
print("---")  


<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58>
---
groups    Coding
num           12
Name: 2, dtype: object
---
   groups  num
0  Movies   46
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64


## 將變數當作屬性選擇

In [16]:
print(select_df)
print("---")  
print(select_df["num"]) # 各組的人數  
print("---")  
print(select_df.num) # 各組的人數  

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64


## loc 

In [12]:
#loc <index>
import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict_data = {"groups": groups,  
        "num": num
       }
select_df = pd.DataFrame(dict_data)
print(select_df)
print('---------------- row')
print(select_df.loc[2])
print('---------------- rows')
print(select_df.loc[2:3])
print('---------------- error')

try:
    print(select_df.loc[6])
except KeyError:
    print('error ! ')
    
print('----------------[1:,"num"]')
print((select_df.loc[2:3,'num']))    
print('----------------')
print((select_df.loc[:,'num']>10))
print('----------------')
print(type(select_df.loc[:,'num']>10))


    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
---------------- row
groups    Coding
num           12
Name: 2, dtype: object
---------------- rows
    groups  num
2   Coding   12
3  Fishing   12
---------------- error
error ! 
----------------[1:,"num"]
2    12
3    12
Name: num, dtype: int64
----------------
0     True
1    False
2     True
3     True
4    False
5     True
Name: num, dtype: bool
----------------
<class 'pandas.core.series.Series'>


In [25]:
import pandas as pd
'''
iloc和loc（列切片及行切片）
'''

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict_data = {"groups": groups,  
        "num": num
       }
select_df = pd.DataFrame(dict_data)
print(select_df)
print("---[2]")  
print(select_df.iloc[2]) # 第二列  
print("---[2, 1]")  
print(select_df.iloc[2, 1]) # 第一列第二欄：組的人數  
print("---[0:1,:]")  
print(select_df.iloc[0:1,:]) # 第一列：組的組名與人數  
#print("---[:,1]")  
#print(select_df.iloc[:,1]) # 第二欄：各組的人數  
print("***********************************")  

print('---------------- [2]')
print(select_df.loc[2])
print('---------------- [2:3,:]')
print(select_df.loc[2:3,:])
print("---------------- [0:1,'num']")
print(select_df.loc[0:1,'num']) 
print('---------------- ')

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
---[2]
groups    Coding
num           12
Name: 2, dtype: object
---[2, 1]
12
---[0:1,:]
   groups  num
0  Movies   46
***********************************
---------------- [2]
groups    Coding
num           12
Name: 2, dtype: object
---------------- [2:3,:]
    groups  num
2   Coding   12
3  Fishing   12
---------------- [0:1,'num']
0    46
1     8
Name: num, dtype: int64
---------------- 


## 用布林值來塞選

In [18]:
import pandas as pd
groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

tmp_dict = {'group':groups,
           'num':num}
select_df = pd.DataFrame(tmp_dict)
out_df = select_df[select_df.loc[:,'num']>10] #選擇超過十人的組
print(out_df)
'''
test = pd.Series([True,True,True,True,True,True])
print(type(test))
print(select_df[test])
'''

     group  num
0   Movies   46
2   Coding   12
3  Fishing   12
5  cooking   58


'\ntest = pd.Series([True,True,True,True,True,True])\nprint(type(test))\nprint(select_df[test])\n'

## 資料排序 

## sort_index

In [20]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

data_dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(data_dict)
print(select_df)
print("-------------")
select_df_sort = select_df.sort_index(axis = 1, ascending = True) # 透過索引值做排序，axis 可以指定第幾欄，ascending 用於設定升冪或降密 
print("-------------")
print(select_df_sort)


    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
-------------
-------------
    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


## sort_values

In [83]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(dict)
print(select_df)
print("--------------")
select_df_data =select_df.sort_values(by = 'num') #透過指定欄位的數值排序 
print(select_df_data)


    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
--------------
    groups  num
4  Dancing    6
1   Sports    8
2   Coding   12
3  Fishing   12
0   Movies   46
5  cooking   58


# DataFrame 處理遺漏值

## 判斷是否為空值 

In [24]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd  
df = pd.read_csv('data\shop_list.csv')  
print(df)


   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3       NaN   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         NaN


In [25]:
print(df.loc[:, "shop name"].isnull()) # 判斷哪些店名是遺失值  
print("---")  
print(df.loc[:, "maket size"].notnull()) # 判斷哪些市場規模不是遺失值

0    False
1    False
2     True
3    False
4    False
Name: shop name, dtype: bool
---
0     True
1     True
2     True
3     True
4    False
Name: maket size, dtype: bool


In [48]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print(df)
print('-------------------------')
print (df.loc['d']  )


   a  b  c
d  1  2  3
e  4  5  6
-------------------------
a    1
b    2
c    3
Name: d, dtype: int64


In [117]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print(df)
print("-------------")
print (df.loc['d',['b','c']] ) # 行,列

   a  b  c
d  1  2  3
e  4  5  6
-------------
b    2
c    3
Name: d, dtype: int64


# iloc

In [49]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns) 
print(df)
print("-------------")
print (df.iloc[1::] ) 

   a  b  c
0  1  2  3
1  4  5  6
-------------
a    4
b    5
c    6
Name: 1, dtype: int64


## loc vs iloc

In [54]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print(df)
print("-------------")
print (df.iloc[1:] )  #index way
print("-------------")
print (df.iloc[:,[1]])  
print("-------------")
print (df.loc[:,['b']])  

   a  b  c
d  1  2  3
e  4  5  6
-------------
   a  b  c
e  4  5  6
-------------
   b
d  2
e  5
-------------
   b
d  2
e  5


# 回到處理空值

In [55]:
print(select_df.loc[:, "shop name"].isnull()) # 判斷哪些店名是遺失值  
print("---")  
print(select_df.loc[:, "maket size"].notnull()) # 判斷哪些市場規模不是遺失值

KeyError: 'the label [shop name] is not in the [columns]'

In [57]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd  
df = pd.read_csv('data\shop_list.csv')  
print("---data") 
print(df)

print("---有遺失值的觀測值都刪除 ")  
drop_value = df.dropna() # 有遺失值的觀測值都刪除  
print(drop_value)  
print("---有遺失值的觀測值填補 0")  
filled_value = df.fillna(0) # 有遺失值的觀測值填補 0  
print(filled_value)  
print("---依欄位填補遺失值")  
filled_value_column = df.fillna({"shop name": "NULL", "maket size":10}) # 依欄位填補遺失值  
print(filled_value_column)  

---data
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3       NaN   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         NaN
---有遺失值的觀測值都刪除 
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
3        4    Pchome    300000.0
---有遺失值的觀測值填補 0
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3         0   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         0.0
---依欄位填補遺失值
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3      NULL   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo        10.0
