# Numpy

In [148]:
import numpy as np 
np.__version__

"""
ref:
1. http://cs231n.github.io/python-numpy-tutorial/#python-classes
2. https://www.datacamp.com/community/tutorials/python-numpy-tutorial#array
"""

'\nref:\n1. http://cs231n.github.io/python-numpy-tutorial/#python-classes\n2. https://www.datacamp.com/community/tutorials/python-numpy-tutorial#array\n'

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))   
print(a.ndim)
print(a.data)             # Print out memory address
print(a.shape)            # Prints "(3,)" 可看出多少維度
print("------- 1D ---------")
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
print("------ 2D ----------")
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   
print("------ 3D ----------")
c = np.array([[[ 1 , 2 , 3 , 4] ,[ 5 , 6 , 7 , 8]],[[ 1,  2,  3 , 4],[ 9 ,10 ,11 ,12]]])
print(c)
print(c.shape) 
print(c[0,0,2]) 


<class 'numpy.ndarray'>
1
(3,)
------- 1D ---------
1 2 3
[5 2 3]
------ 2D ----------
(2, 3)
1 2 4
------ 3D ----------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
(2, 2, 4)
3


In [5]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a) 
print('--------------------')
b = np.ones((1,2))    # Create an array of all ones
print(b)  
print('--------------------')
d = np.eye(3)         # Create a 2x2 identity matrix
print(d)  

[[0. 0.]
 [0. 0.]]
--------------------
[[1. 1.]]
--------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Slicing

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('--------------------')
print(a.data)
print('--------------------')
print(a.shape)
print('--------------------')
print(a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
--------------------
(3, 4)
--------------------
2


In [7]:
b = a[:2, 1:3]
print(b)
print('--------------------')
print(b.data)
print('--------------------')
print(a[0, 1]) 
print('--------------------')
b[0, 0] = 77
print(b)
print('--------------------')
print(a[0, 1]) 

[[2 3]
 [6 7]]
--------------------
--------------------
2
--------------------
[[77  3]
 [ 6  7]]
--------------------
77


In [9]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 
print(x)
print('------------------------')
print(v)
print('------------------------')
print(y)
print('------------------------')
for i in range(4):
    print(str(i)+'th row')
    y[i, :] = x[i, :] + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------------------
[1 0 1]
------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------------------
0th row
1th row
2th row
3th row
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(v )          

# Pandas 

### 資料前處理以及 DataFrame 所用

#  1.1建立 Series

## array

In [23]:
import pandas as pd # 引用套件並縮寫為 pd
cars = ["BMW", "BENZ", "Toyota", "Nissan", "Lexus"]

select = pd.Series(cars)  
print(select)  

0       BMW
1      BENZ
2    Toyota
3    Nissan
4     Lexus
dtype: object


## dict

In [27]:
import pandas as pd

dict_data = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict_data, index = dict.keys()) # 排序與原 dict 相同  
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']]) 

Taipei
=====
1
=====
factory    Taipei
sensor2         2
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         1
sensor3         3
dtype: object


## 資料為單一資料

In [29]:
import pandas as pd

cars = "BENZ"  
select = pd.Series(cars, index = range(5))  
print(select) 

0    BENZ
1    BENZ
2    BENZ
3    BENZ
4    BENZ
dtype: object


# 1.2 Series 的操作

## 資料選擇與篩選

In [34]:
import pandas as pd

dict_data = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor1": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict_data, index = dict.keys()) # 排序與原 dict 相同  
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']])  

Taipei
=====
2
=====
factory    Taipei
sensor2       NaN
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         2
sensor3         3
dtype: object


## 資料切片 

In [35]:
import pandas as pd

dict = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict, index = dict.keys()) # 排序與原 dict 相同  
print(select[:2])  
print("=====")  
print(select['sensor2':])  

factory    Taipei
sensor1         1
dtype: object
=====
sensor2    2
sensor3    3
sensor4    4
sensor5    5
dtype: object


# 2.DataFrame

## dict

In [37]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
       }

select_df = pd.DataFrame(dict)

print(select_df) # 看看資料框的外觀  

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


## Array

In [4]:
import pandas as pd

arr = groups = [["Movies", 46],["Sports", 8], ["Coding", 12], ["Fishing",12], ["Dancing",6], ["cooking",8]]

df = pd.DataFrame(arr, columns = ["name", "num"]) # 指定欄標籤名稱  
print(df)  

      name  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking    8


# 2.2 DataFrame 的操作

In [5]:
# Pandas 的 data frame 資料結構有一些方法或屬性

import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(dict)
print("---shape")
print(select_df.shape) # 回傳列數與欄數  
print("---describe")  
print(select_df.describe()) # 回傳描述性統計  
print("---head")  
print(select_df.head(3)) # 回傳前三筆觀測值  
print("---tail")  
print(select_df.tail(3)) # 回傳後三筆觀測值  
print("---columns")  
print(select_df.columns) # 回傳欄位名稱  
print("---index")  
print(select_df.index) # 回傳 index  
print("---info")  
print(select_df.info) # 回傳資料內容  

---shape
(6, 2)
---describe
             num
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
---head
   groups  num
0  Movies   46
1  Sports    8
2  Coding   12
---tail
    groups  num
3  Fishing   12
4  Dancing    6
5  cooking   58
---columns
Index(['groups', 'num'], dtype='object')
---index
RangeIndex(start=0, stop=6, step=1)
---info
<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58>


##  資料選擇與篩選 

In [6]:
import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
       }
select_df = pd.DataFrame(dict)

print(select_df.info)
print("---")  
print(select_df.iloc[2, 1]) # 第一列第二欄：組的人數  
print("---")  
print(select_df.iloc[0:1,:]) # 第一列：組的組名與人數  
print("---")  
print(select_df.iloc[:,1]) # 第二欄：各組的人數  
print("---")  
print(select_df["num"]) # 各組的人數  
print("---")  
print(select_df.num) # 各組的人數  

<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58>
---
12
---
   groups  num
0  Movies   46
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64


## 用布林值來塞選

In [55]:
import pandas as pd
groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

tmp_dict = {'group':groups,
           'num':num}
select_df = pd.DataFrame(tmp_dict)
out_df = select_df[select_df.loc[:,'num']>10]
print(out_df)

     group  num
0   Movies   46
2   Coding   12
3  Fishing   12
5  cooking   58


## 資料排序 

## sort_index

In [78]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

data_dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(data_dict)
print(select_df)
select_df.sort_index(axis = 1, ascending = True) # 透過索引值做排序，axis 可以指定第幾欄，ascending 用於設定升冪或降密 
print("-------------")

df_data = pd.DataFrame([1, 2, 3, 4, 5], index=[100, 29, 234, 1, 150], columns=['A'])
#df_data.sort_index(axis = 0, ascending = True)
print(df_data)
print('---------------------')
print(df_data.sort_index(axis = 0, ascending = True))

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
-------------
     A
100  1
29   2
234  3
1    4
150  5
---------------------
     A
1    4
29   2
100  1
150  5
234  3


## sort_values

In [83]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(dict)
print(select_df)
print("--------------")
select_df_data =select_df.sort_values(by = 'num') #透過指定欄位的數值排序 
print(select_df_data)


    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
--------------
    groups  num
4  Dancing    6
1   Sports    8
2   Coding   12
3  Fishing   12
0   Movies   46
5  cooking   58


# DataFrame 處理遺漏值

## 判斷是否為空值 

In [85]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd  
df = pd.read_csv('data\shop_list2.csv')  
print(df)

# 讀取後放入 DataFrame
select_df = pd.DataFrame(df)

   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3       NaN   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         NaN


In [94]:
print(select_df.loc[:, "shop name"].isnull()) # 判斷哪些店名是遺失值  
print("---")  
print(select_df.loc[:, "maket size"].notnull()) # 判斷哪些市場規模不是遺失值

0    False
1    False
2     True
3    False
4    False
Name: shop name, dtype: bool
---
0     True
1     True
2     True
3     True
4    False
Name: maket size, dtype: bool


## loc

In [134]:
#source : https://blog.csdn.net/xw_classmate/article/details/51333646
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = [0,1]  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print (df )
print(df.loc[0]) #印出 index 的那一行
print('------------------')



   a  b  c
0  1  2  3
1  4  5  6
a    1
b    2
c    3
Name: 0, dtype: int64
------------------


In [103]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print(df)
print (df.loc['d'] ) 
 

   a  b  c
d  1  2  3
e  4  5  6
a    1
b    2
c    3
Name: d, dtype: int64


In [105]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print (df.loc['a']  )

KeyError: 'the label [a] is not in the [index]'

In [111]:
import pandas as pd  
data = [[1,2,3],[4,5,6],[7,8,9]]  
index = ['d','e','f']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)
print(df)
print("-------------")
print (df.loc['e':] )

   a  b  c
d  1  2  3
e  4  5  6
f  7  8  9
-------------
   a  b  c
e  4  5  6
f  7  8  9


In [117]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print(df)
print("-------------")
print (df.loc['d',['b','c']] ) # 行,列

   a  b  c
d  1  2  3
e  4  5  6
-------------
b    2
c    3
Name: d, dtype: int64


# iloc

In [133]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns) 
print(df)
print("-------------")
print (df.iloc['e'] ) 

   a  b  c
d  1  2  3
e  4  5  6
-------------


TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [e] of <class 'str'>

In [132]:
import pandas as pd  
data = [[1,2,3],[4,5,6]]  
index = ['d','e']  
columns=['a','b','c']  
df = pd.DataFrame(data=data, index=index, columns=columns)  
print(df)
print("-------------")
print (df.iloc[1:] )  #index way
print("-------------")
print (df.iloc[:,[1]])  

   a  b  c
d  1  2  3
e  4  5  6
-------------
   a  b  c
e  4  5  6
-------------
   b
d  2
e  5


# ix

In [135]:
print (df.ix[1])

a    4
b    5
c    6
Name: 1, dtype: int64


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


# 回到處理空值

In [136]:
print(select_df.loc[:, "shop name"].isnull()) # 判斷哪些店名是遺失值  
print("---")  
print(select_df.loc[:, "maket size"].notnull()) # 判斷哪些市場規模不是遺失值

0    False
1    False
2     True
3    False
4    False
Name: shop name, dtype: bool
---
0     True
1     True
2     True
3     True
4    False
Name: maket size, dtype: bool


In [145]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd  
df = pd.read_csv('data\shop_list2.csv')  
print("---data") 
print(df)

# 讀取後放入 DataFrame
select_df = pd.DataFrame(df)
print("---有遺失值的觀測值都刪除 ")  
drop_value = select_df.dropna() # 有遺失值的觀測值都刪除  
print(drop_value)  
print("---有遺失值的觀測值填補 0")  
filled_value = select_df.fillna(0) # 有遺失值的觀測值填補 0  
print(filled_value)  
print("---依欄位填補遺失值")  
filled_value_column = select_df.fillna({"shop name": "NULL", "maket size":10}) # 依欄位填補遺失值  
print(filled_value_column)  

---data
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3       NaN   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         NaN
---有遺失值的觀測值都刪除 
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
3        4    Pchome    300000.0
---有遺失值的觀測值填補 0
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3         0   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         0.0
---依欄位填補遺失值
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3      NULL   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo        10.0
