# Numpy

In [ ]:
import numpy as np 
np.__version__

'''
ref:
1. http://cs231n.github.io/python-numpy-tutorial/#python-classes
2. https://www.datacamp.com/community/tutorials/python-numpy-tutorial#array
'''

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))   
print(a.ndim)
print(a.data)             # Print out memory address
print(a.shape)            # Prints "(3,)" 可看出多少維度
print("------- 1D ---------")
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"
print("------ 2D ----------")
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   
print("------ 3D ----------")
c = np.array([[[ 1 , 2 , 3 , 4] ,[ 5 , 6 , 7 , 8]],[[ 1,  2,  3 , 4],[ 9 ,10 ,11 ,12]]])
print(c)
print(c.shape) 
print(c[0,0,2]) 


<class 'numpy.ndarray'>
1
(3,)
------- 1D ---------
1 2 3
[5 2 3]
------ 2D ----------
(2, 3)
1 2 4
------ 3D ----------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
(2, 2, 4)
3


In [5]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a) 
print('--------------------')
b = np.ones((1,2))    # Create an array of all ones
print(b)  
print('--------------------')
d = np.eye(3)         # Create a 2x2 identity matrix
print(d)  

[[0. 0.]
 [0. 0.]]
--------------------
[[1. 1.]]
--------------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Slicing

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print('--------------------')
print(a.data)
print('--------------------')
print(a.shape)
print('--------------------')
print(a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
--------------------
(3, 4)
--------------------
2


In [7]:
b = a[:2, 1:3]
print(b)
print('--------------------')
print(b.data)
print('--------------------')
print(a[0, 1]) 
print('--------------------')
b[0, 0] = 77
print(b)
print('--------------------')
print(a[0, 1]) 

[[2 3]
 [6 7]]
--------------------
--------------------
2
--------------------
[[77  3]
 [ 6  7]]
--------------------
77


In [9]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 
print(x)
print('------------------------')
print(v)
print('------------------------')
print(y)
print('------------------------')
for i in range(4):
    print(str(i)+'th row')
    y[i, :] = x[i, :] + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------------------
[1 0 1]
------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------------------
0th row
1th row
2th row
3th row
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(v )          

# Pandas 

### 資料前處理以及 DataFrame 所用

#  1.1建立 Series

## array

In [23]:
import pandas as pd # 引用套件並縮寫為 pd
cars = ["BMW", "BENZ", "Toyota", "Nissan", "Lexus"]

select = pd.Series(cars)  
print(select)  

0       BMW
1      BENZ
2    Toyota
3    Nissan
4     Lexus
dtype: object


## dict

In [27]:
import pandas as pd

dict_data = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict_data, index = dict.keys()) # 排序與原 dict 相同  
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']]) 

Taipei
=====
1
=====
factory    Taipei
sensor2         2
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         1
sensor3         3
dtype: object


## 資料為單一資料

In [29]:
import pandas as pd

cars = "BENZ"  
select = pd.Series(cars, index = range(5))  
print(select) 

0    BENZ
1    BENZ
2    BENZ
3    BENZ
4    BENZ
dtype: object


# 1.2 Series 的操作

## 資料選擇與篩選

In [34]:
import pandas as pd

dict_data = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor1": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict_data, index = dict.keys()) # 排序與原 dict 相同  
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']])  

Taipei
=====
2
=====
factory    Taipei
sensor2       NaN
sensor4         4
dtype: object
=====
factory    Taipei
sensor1         2
sensor3         3
dtype: object


## 資料切片 

In [35]:
import pandas as pd

dict = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict, index = dict.keys()) # 排序與原 dict 相同  
print(select[:2])  
print("=====")  
print(select['sensor2':])  

factory    Taipei
sensor1         1
dtype: object
=====
sensor2    2
sensor3    3
sensor4    4
sensor5    5
dtype: object


# 2.DataFrame

## dict

In [37]:
import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
       }

select_df = pd.DataFrame(dict)

print(select_df) # 看看資料框的外觀  

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58


## Array

In [38]:
import pandas as pd

arr = groups = [["Movies", 46],["Sports", 8], ["Coding", 12], ["Fishing",12], ["Dancing",6], ["cooking",8]]

df = pd.DataFrame(arr, columns = ["name", "num"]) # 指定欄標籤名稱  
print(df)  

      name  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking    8


# 2.2 DataFrame 的操作

In [40]:
# Pandas 的 data frame 資料結構有一些方法或屬性

import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(dict)
print("---shape")
print(select_df.shape) # 回傳列數與欄數  
print("---describe")  
print(select_df.describe()) # 回傳描述性統計  
print("---head")  
print(select_df.head(3)) # 回傳前三筆觀測值  
print("---tail")  
print(select_df.tail(3)) # 回傳後三筆觀測值  
print("---columns")  
print(select_df.columns) # 回傳欄位名稱  
print("---index")  
print(select_df.index) # 回傳 index  
print("---info")  
print(select_df.info) # 回傳資料內容  

---shape
(6, 2)
---describe
             num
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
---head
   groups  num
0  Movies   46
1  Sports    8
2  Coding   12
---tail
    groups  num
3  Fishing   12
4  Dancing    6
5  cooking   58
---columns
Index(['groups', 'num'], dtype='object')
---index
RangeIndex(start=0, stop=6, step=1)
---info
<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58>


##  資料選擇與篩選 

In [48]:
import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
       }
select_df = pd.DataFrame(dict)

print(select_df.info)
print("---")  
print(select_df.iloc[2, 1]) # 第一列第二欄：組的人數  
print("---")  
print(select_df.iloc[0:1,:]) # 第一列：組的組名與人數  
print("---")  
print(select_df.iloc[:,1]) # 第二欄：各組的人數  
print("---")  
print(select_df["num"]) # 各組的人數  
print("---")  
print(select_df.num) # 各組的人數  

<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58>
---
12
---
   groups  num
0  Movies   46
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
---
0    46
1     8
2    12
3    12
4     6
5    58
Name: num, dtype: int64
