# 字串轉為數字

In [30]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd  
df = pd.read_csv('data\\realEstate.csv')  
print(df)

   id marriage         age  income WantHouse
0   1  married     teenage     low         y
1   2  married  middle age    high         N
2   3   single  middle age    high         N
3   4   single     teenage    high         y
4   5  married  middle age  middle         y
5   6   single  middle age     low         y
6   7   single     teenage    high         N
7   8  married     teenage    high         N
8   9  married  middle age    high         y
9  10  married     teenage    high         y


## Label_encoder

In [23]:
from sklearn import preprocessing

data= [1, 2, 2, 6]
le = preprocessing.LabelEncoder() #obj
le.fit(data)  
print('-----------classes_')
print(le.classes_)
print('-----------transform')
tra_le = le.transform(data) #encoder
print(tra_le)
print('-----------inverse_transform')
inver_tra_le = le.inverse_transform(tra_le) #look up earch encoder
print(inver_tra_le)

-----------classes_
[1 2 6]
-----------transform
[0 1 1 2]
-----------inverse_transform
[1 2 2 6]


C:\Users\USER\Anaconda3\envs\myenv\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [28]:
le = preprocessing.LabelEncoder() #obj
le.fit(df['marriage'])  
print('-----------classes_')
print(le.classes_)
print('-----------transform')
tra_le = le.transform(df['marriage']) #encoder
print(tra_le)
df['marriage'] = tra_le

-----------classes_
['married' 'single']
-----------transform
[0 0 1 1 0 1 1 0 0 0]


In [32]:
for col in ['marriage','age','income','WantHouse']:
    le = preprocessing.LabelEncoder() #obj
    le.fit(df[col])  
    tra_le = le.transform(df[col]) #encoder
    df[col] = tra_le

In [33]:
df

id  marriage  age  income  WantHouse
0   1         0    1       1          1
1   2         0    0       0          0
2   3         1    0       0          0
3   4         1    1       0          1
4   5         0    0       2          1
5   6         1    0       1          1
6   7         1    1       0          0
7   8         0    1       0          0
8   9         0    0       0          1
9  10         0    1       0          1

# Imputer

In [41]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer

df = pd.read_csv('data\shop_list.csv')  
print("---data") 
print(type(df))
print(df)
'''
imp = Imputer(missing_values='NaN', strategy='mean')
after_df = imp.fit_transform(df)
'''
del df['shop name']
imp = Imputer(missing_values='NaN', strategy='mean')
after_df = imp.fit_transform(df)
np.set_printoptions(suppress=True) #輸出的上 移除 科學符號 e
print(after_df)
#print(help(imp))

---data
<class 'pandas.core.frame.DataFrame'>
   shop id shop name  maket size
0        1  Wal mart   3000000.0
1        2    Costco   2000000.0
2        3       NaN   1500000.0
3        4    Pchome    300000.0
4        5     Yahoo         NaN
[[      1. 3000000.]
 [      2. 2000000.]
 [      3. 1500000.]
 [      4.  300000.]
 [      5. 1700000.]]
Help on Imputer in module sklearn.preprocessing.imputation object:

class Imputer(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <imputation>`.
 |  
 |  Parameters
 |  ----------
 |  missing_values : integer or "NaN", optional (default="NaN")
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For missing values encoded as np.nan,
 |      use the string value "NaN".
 |  
 |  strategy : string, optional (default="mean")
 |      The imputation strategy.
 |  
 |      - If "mean"